/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.stat.product;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Invoice;
import model.InvoiceProduct;
import model.Product;
import model.User;
import view.user.LoginFrm;
import view.user.ManagementFrm;

/**
 *
 * @author NGUYEN VAN CANH
 */
public class DetailInvoiceFrm extends javax.swing.JFrame {

    private User user;
    private Product product;
    public static Date startDate;
    public static Date endDate;
    public static DefaultTableModel model;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private DetailInvoiceFrm detailInvoiceFrame;
    private Invoice invoice;
    public static int idInvoice;
    public static ArrayList<InvoiceProduct> myInvoiceProduct;

    /**
     * Creates new form DetailInvoiceFrm
     */
    public DetailInvoiceFrm(User user, Invoice invoice, ArrayList<InvoiceProduct> myInvoiceProduct) throws SQLException {
        super("Manager Home");
        initComponents();
        this.user = user;
        this.invoice = invoice;
        Invoice iv=new Invoice();
        float total=0;
        for (InvoiceProduct ip : myInvoiceProduct) {
            if(ip.getInvoice().getId()==invoice.getId()){
               iv=ip.getInvoice();
            break;
            }
        }
        idInvoiceLabel.setText("Mã hóa đơn: "+iv.getId());
                idSubLabel.setText("Mã đại lý: "+ iv.getS().getId());
                idUserLabel.setText("Mã người tạo: "+ iv.getU().getId());
                nameSubLabel.setText("Tên đại lý: "+iv.getS().getName());
                nameUserLabel.setText("Tên người tạo: "+iv.getU().getFullName());
                String pd=sdf.format(iv.getPaymentdate());
                paymentDateLabel.setText("Ngày xuất: "+ pd);
        List<InvoiceProduct> myInvoiceProduct2 = new ArrayList<>();
        for (InvoiceProduct ip : myInvoiceProduct) {
               if(ip.getInvoice().getId()==invoice.getId()){
                   myInvoiceProduct2.add(ip);
                    total+=ip.getIncome();
                } 
        }
        totalIncomeLabel.setText("TỔNG: "+ total);
        fullnameJLabel.setText("Tài khoản " + user.getFullName());
        model = (DefaultTableModel) detailInvoiceTable.getModel();
        detailInvoiceTable.setDefaultEditor(Object.class, null);
        displayDetailInvoices(myInvoiceProduct2);
    }

    /**
     * This method is called from within the constructor to initialize the
     * form.WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * @param myInvoiceProduct
     */
    public int i=1;
    private void displayDetailInvoices(List<InvoiceProduct> myInvoiceProduct) {
        for (InvoiceProduct invoiceProduct : myInvoiceProduct) {
            Object[] rowData = {
                i++,
                invoiceProduct.getProduct().getId(),
                invoiceProduct.getProduct().getName(),
                invoiceProduct.getQuanity(),
                invoiceProduct.getPrice(),
                invoiceProduct.getIncome()
            };
            model.addRow(rowData);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailInvoiceTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fullnameJLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idInvoiceLabel = new javax.swing.JLabel();
        idSubLabel = new javax.swing.JLabel();
        idUserLabel = new javax.swing.JLabel();
        nameUserLabel = new javax.swing.JLabel();
        nameSubLabel = new javax.swing.JLabel();
        paymentDateLabel = new javax.swing.JLabel();
        totalIncomeLabel = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        statButton.setText("Xem thống kê");
        statButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Quản lý");

        detailInvoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Id", "Name", "Quantity", "Price", "Income"
            }
        ));
        jScrollPane1.setViewportView(detailInvoiceTable);
        if (detailInvoiceTable.getColumnModel().getColumnCount() > 0) {
            detailInvoiceTable.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel1.setText("CHI TIẾT HÓA ĐƠN");

        fullnameJLabel.setText("Tài khoản Manager");

        logoutButton.setText("Đăng xuất");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jButton4.setText("Đổi mật khẩu");

        jLabel3.setText("TÍNH NĂNG");

        idInvoiceLabel.setText("Mã hóa đơn:");

        idSubLabel.setText("Mã đại lý:");

        idUserLabel.setText("Mã người tạo:");

        nameUserLabel.setText("Tên người tạo:");

        nameSubLabel.setText("Tên đại lý:");

        paymentDateLabel.setText("Ngày xuất:");

        totalIncomeLabel.setText("TỔNG: ");

        returnButton.setText("Quay lại");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalIncomeLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idInvoiceLabel)
                                    .addComponent(paymentDateLabel))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idSubLabel)
                                    .addComponent(nameSubLabel))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameUserLabel)
                                    .addComponent(idUserLabel)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 988, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fullnameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(fullnameJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logoutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(idInvoiceLabel)
                    .addComponent(idSubLabel)
                    .addComponent(idUserLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameUserLabel)
                            .addComponent(nameSubLabel)
                            .addComponent(paymentDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalIncomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(returnButton)))
                .addContainerGap(648, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statButtonActionPerformed
        SelectStatFrm selectstatFrm = new SelectStatFrm(user);
        selectstatFrm.setVisible(true);
        dispose();
    }//GEN-LAST:event_statButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LoginFrm loginFrm = new LoginFrm();
        loginFrm.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        ManagementFrm managementFrm=new ManagementFrm(user);
        managementFrm.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        User user = new User();
        Invoice invoice = new Invoice();
        ArrayList<InvoiceProduct> invoiceproduct = new ArrayList<>();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailInvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailInvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailInvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailInvoiceFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DetailInvoiceFrm(user, invoice, invoiceproduct).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DetailInvoiceFrm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable detailInvoiceTable;
    private javax.swing.JLabel fullnameJLabel;
    private javax.swing.JLabel idInvoiceLabel;
    private javax.swing.JLabel idSubLabel;
    private javax.swing.JLabel idUserLabel;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameSubLabel;
    private javax.swing.JLabel nameUserLabel;
    private javax.swing.JLabel paymentDateLabel;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton statButton;
    private javax.swing.JLabel totalIncomeLabel;
    // End of variables declaration//GEN-END:variables
}
